/** @type {import('cz-git').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
      type: '選擇你要提交的類型：',
      scope: '選擇或輸入影響範圍（可選，直接按 Enter 跳過）：',
      customScope: '請輸入自訂的影響範圍：',
      subject: '填寫簡短的 commit 訊息：\n',
      body: '填寫詳細描述（可選，直接按 Enter 跳過）：\n',
      breaking: '列出重大變更（BREAKING CHANGES，可選）：\n',
      footerPrefixesSelect: '選擇關聯 issue 前綴（可選）：',
      customFooterPrefix: '輸入自訂 issue 前綴：',
      footer: '列出關聯的 issues（例如: #31, #34，可選）：\n',
      confirmCommit: '確定要使用以上訊息進行提交嗎？',
    },
    types: [
      { value: 'feat',     name: 'feat:     ✨  新增功能 (feature)' },
      { value: 'fix',      name: 'fix:      🐛  修復問題 (bug fix)' },
      { value: 'docs',     name: 'docs:     📝  文件調整 (documentation)' },
      { value: 'style',    name: 'style:    💄  程式碼格式 (formatting, white-space)' },
      { value: 'refactor', name: 'refactor: ♻️   程式碼重構 (neither fixes a bug nor adds a feature)' },
      { value: 'perf',     name: 'perf:     ⚡️  效能優化 (improves performance)' },
      { value: 'test',     name: 'test:     ✅  測試相關 (adding or correcting tests)' },
      { value: 'build',    name: 'build:    📦️  建置/依賴 (build system or external dependencies)' },
      { value: 'ci',       name: 'ci:       🎡  CI/CD 設定 (continuous integration configuration)' },
      { value: 'chore',    name: 'chore:    🔨  日常雜項 (other changes that don\'t modify src/test)' },
      { value: 'revert',   name: 'revert:   ⏪️  還原版本 (revert previous commit)' },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    themeColorCode: '',
    scopes: [],
    enableMultipleScopes: false,
    scopeEnumSeparator: ',',
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeNodes: ['!'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: ['breaking', 'footer', 'footerPrefix'],
    issuePrefixes: [{ value: 'closed', name: 'closed:   關閉 issues' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
};
